name: ğŸ” License Notification Cron

on:
  schedule:
    - cron: '0 4,9 * * *' #7AM & 4PM Thailand time
  workflow_dispatch:
    

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¡ Ping notify API
        run: curl -s "https://sgw-project-manager.netlify.app/api/license/notify?secret=${{ secrets.CRON_SECRET }}"
